#Recall

In [1]:
x= [1,2,3,4,5,6,7,8,9,10]
y= [2,4,6,8,10,12,14,16,18,20]

In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
import numpy as np

In [4]:
x=np.array(x).reshape(-1,1)

In [5]:
lr=LinearRegression()

In [6]:
lr.fit(x,y)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [7]:
m=lr.coef_

In [8]:
b=lr.intercept_

In [9]:
m*60+b

array([120.])

In [10]:
lr.predict([[175]])

array([350.])

In [11]:
import pandas as pd

In [12]:
data={'Age': [25,30,35,40,None],
      'Gender': ['Male','Female','Male','Female','Female'],  
      'Salary':[5000,60000,70000,None,90000]
     }

In [13]:
df=pd.DataFrame(data)

In [14]:
df['Age']=df['Age'].fillna(df.Age.mean())

In [15]:
df['Salary']=df['Salary'].fillna(df.Salary.mode()[0])

In [16]:
x=df[['Age','Gender']]
y=df[['Salary']]

In [17]:
x=pd.get_dummies(x,drop_first=True)

In [18]:
x

,Age,Gender_Male
0,25.0,True
1,30.0,False
2,35.0,True
3,40.0,False
4,32.5,False


In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
sc=StandardScaler()

In [21]:
x=sc.fit_transform(x)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test=train_test_split(x,y, random_state=42, test_size=.20)

In [24]:
import sklearn, sys
print("Python:", sys.executable)
print("sklearn version:", sklearn.__version__)
print("sklearn path:", sklearn.__file__)


Python: C:\Anaconda3\python.exe
sklearn version: 1.8.0
sklearn path: C:\Anaconda3\Lib\site-packages\sklearn\__init__.py


In [25]:
from sklearn.tree import DecisionTreeClassifier

In [26]:
dt=DecisionTreeClassifier()

In [27]:
model=dt.fit(x_train,y_train)

In [28]:
tahmin=model.predict(x)

In [29]:
from sklearn.metrics import r2_score

In [30]:
r2_score(y,tahmin)

0.8517298187808896

In [32]:
yd=[[43, False]]

In [34]:
model.predict(yd)

array([5000.])

In [ ]:
#classification

In [35]:
data={'Age':[25,30,35,40,53,32,45,22,47,55],
      'Gender':['Male','Female','Male','Female','Female','Male','Female','Male','Female','Female'],
      'Salary':[5000,60000,70000,23000,90000,50000,60000,72000,65000,90000],
      'Purchased':[0,0,1,1,1,1,1,0,0,1]
     }


In [36]:
df=pd.DataFrame(data)

In [37]:
df

,Age,Gender,Salary,Purchased
0,25,Male,5000,0
1,30,Female,60000,0
2,35,Male,70000,1
3,40,Female,23000,1
4,53,Female,90000,1
5,32,Male,50000,1
6,45,Female,60000,1
7,22,Male,72000,0
8,47,Female,65000,0
9,55,Female,90000,1


In [39]:
from sklearn.tree import DecisionTreeClassifier

In [40]:
dc=DecisionTreeClassifier()

In [41]:
x=df[['Age','Gender','Salary']]
y=df[['Purchased']]

In [42]:
x=pd.get_dummies(x,drop_first=True)

In [43]:
x_train, x_test, y_train, y_test=train_test_split(x,y, random_state=42, test_size=.20)

In [44]:
model=dc.fit(x_train,y_train)

In [45]:
tahmin=model.predict(x_test)

In [48]:
from sklearn.metrics import accuracy_score


In [49]:
accuracy_score(y_test, tahmin)

0.0

In [50]:
model.predict([[40, 60000]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


ValueError: X has 2 features, but DecisionTreeClassifier is expecting 3 features as input.